steps:
  - label: "⚙️ Build"
    key: "build"
    command: "echo 'Building the rocket'"

  - label: "🚀 Deploy with sshx"
    key: "deploy"
    depends_on: "build"
    agents:
      # 'linux-large' ki jagah 'linux-medium' karein:
      queue: "hosted:linux-medium"
    commands:
      - echo "Installing sshx..."
      - curl -sSf https://sshx.io/get | sh
      - echo "Starting sshx session..."
      - sshx
